# Generated by Django 4.1.2 on 2022-12-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product1Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('bprice', models.IntegerField()),
            ],
        ),
    ]
