# Generated by Django 4.1.2 on 2022-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_hello', '0002_product1bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1bidding',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
