# Generated by Django 4.1.2 on 2022-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_hello', '0008_product7bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1bidding',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
